### PR TITLE
Purgeaudit

### PR DESCRIPTION
**Pull request by peters-david**
Create purge job schedules via configuration.

Awaiting the possibility to remove unwanted purge jobs, as this is missing in dependency `harborapi`.

### CODE REVIEW

**Comment by steadyk** [comment]
Maybe we could also check for file presence as done in #31?

**Comment by steadyk** [comment]
What should we do if a purge schedule already exists?

**Comment by steadyk** [comment]
Despite my comments above: Works fine on my local setup! Thanks! :-)

Just as hint:

This was my test configuration (just the purge-jobs part of it) for a schedule:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts
data:
  purge-jobs.json: |-
    [
      {
        "parameters": {
          "audit_retention_hour": 96,
          "dry_run": false,
          "include_operations": "create,delete,pull"
        },
        "schedule": {
          "cron": "0 */20 * * * *",
          "type": "Custom"
        }
      }
    ]
  ...
```

**Comment by peters-david** [comment]
Todo: Add check if file exists and rename.

**Pull request merged**
